### PR TITLE
Bugfix: Typo in volume in a gli; changed AREA to GEOMETRY_AREA in some mmp

### PR DESCRIPTION
**Pull request by MuellerSeb**
found with ogs5py

### CODE REVIEW

**Comment by MuellerSeb** [comment]
https://github.com/GeoStat-Framework/ogs5py_benchmarks/blob/master/benchmarks_FEM_active/LOG.txt#L202

**Comment by wenqing** [comment]
@MuellerSeb  Nice.
It is better to remove that VOLUME entity in gli because it is not used anywhere in the input data.

**Comment by MuellerSeb** [comment]
@wenqing but I think the output is different after the change.
I added the sub-keyword change to this pull-request. See: https://github.com/ufz/ogs5-benchmarks/issues/27

**Comment by MuellerSeb** [comment]
@wenqing : My Fault! The output is the same on my machine. I compared the wrong files. So should I remove this volume, right?

**Pull request merged**
